export const COPYRIGHT_BUILD_YEAR = 2022;
export const COPYRIGHT_AUTHOR = 'Mikhail Konin';
export const COPYRIGHT_LICENSE = 'MIT';
export const GITHUB_LINK = 'https://github.com/KoninMikhail/react-snake-game';
export const GITHUB_LINK_TEXT = 'Star on GitHub';
export const ACTION_TEXT = 'press ENTER to start...';
export const ACTION_TEXT_MOBILE = 'DOUBLE TAP to start...';
export const NOT_FOUND_TEXT = "Don't look for easter eggs, asshole!";
export const ERR_TEXT = 'Error in app';
